language: cpp
dist: xenial
addons:
  apt:
    packages: &general
        - check
        - libboost-dev
        - libreadline-dev
        - libpam0g-dev
        - libssl-dev
        - libhwloc-dev
        - hwloc
        - libxml2-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-4.4', 'g++-4.4']
      env:
        - OUR_CC=gcc-4.4 OUR_CXX=g++-4.4 OUR_GCOV=gcov-4.4

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-4.8', 'g++-4.8']
      env:
        - OUR_CC=gcc-4.8 OUR_CXX=g++-4.8 OUR_GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-5', 'g++-5']
      env:
        - OUR_CC=gcc-5 OUR_CXX=g++-5 OUR_GCOV=gcov-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-6', 'g++-6']
      env:
        - OUR_CC=gcc-6 OUR_CXX=g++-6 OUR_GCOV=gcov-6

install:
    - mkdir -p $HOME/opt/bin
    - ln -s $(which $OUR_GCOV) $HOME/opt/bin/gcov

script:
    - ./autogen.sh
    - CC=$OUR_CC CXX=$OUR_CXX ./configure --with-check --with-pam --enable-acct-x --enable-drmaa --enable-cgroups
    - make -j2 V=0
    - set -o pipefail
    - make check -k V=0 | tee checks.txt
    - make distcheck V=0
    - python parse_cov_results.py checks.txt
    - python cov_file_results.py
